// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDiem.Data;

#nullable disable

namespace QuanLyDiem.Migrations
{
    [DbContext(typeof(QuanLyDiemDbContext))]
    partial class QuanLyDiemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDiem.Models.Entity.ClassGradeSummary", b =>
                {
                    b.Property<string>("SectionClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AttendanceScore")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal>("AttendanceWeight")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal>("MidtermScore")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal>("MidtermWeight")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("SectionClassID", "StudentID");

                    b.HasIndex("StudentID");

                    b.ToTable("ClassGradeSummaries");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.ClassSchedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("RoomID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionClassID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SlotCount")
                        .HasColumnType("int");

                    b.Property<int>("StartSlot")
                        .HasColumnType("int");

                    b.HasKey("ScheduleID");

                    b.HasIndex("SectionClassID");

                    b.ToTable("ClassSchedules");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.Course", b =>
                {
                    b.Property<string>("CourseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalWeight")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal>("ProcessWeight")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.Enrollment", b =>
                {
                    b.Property<string>("SectionClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EnrollmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Grade10")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal>("Grade4")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("LetterGrade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectionClassID", "StudentID");

                    b.HasIndex("StudentID");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.Lecturer", b =>
                {
                    b.Property<string>("LecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LecturerID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.SectionClass", b =>
                {
                    b.Property<string>("SectionClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LecturerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("SemesterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectionClassID");

                    b.HasIndex("CourseID");

                    b.HasIndex("LecturerID");

                    b.ToTable("SectionClasses");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.Student", b =>
                {
                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.SubGradeDetail", b =>
                {
                    b.Property<int>("SubGradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubGradeID"));

                    b.Property<string>("AssessmentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssessmentNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("SectionClassID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("SubGradeID");

                    b.HasIndex("SectionClassID");

                    b.HasIndex("StudentID");

                    b.ToTable("SubGradeDetails");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.ClassGradeSummary", b =>
                {
                    b.HasOne("QuanLyDiem.Models.Entity.SectionClass", "SectionClass")
                        .WithMany()
                        .HasForeignKey("SectionClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDiem.Models.Entity.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionClass");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.ClassSchedule", b =>
                {
                    b.HasOne("QuanLyDiem.Models.Entity.SectionClass", "SectionClass")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("SectionClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionClass");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.Enrollment", b =>
                {
                    b.HasOne("QuanLyDiem.Models.Entity.SectionClass", "SectionClass")
                        .WithMany()
                        .HasForeignKey("SectionClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDiem.Models.Entity.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionClass");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.Lecturer", b =>
                {
                    b.HasOne("QuanLyDiem.Models.Entity.User", "User")
                        .WithOne("Lecturer")
                        .HasForeignKey("QuanLyDiem.Models.Entity.Lecturer", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.SectionClass", b =>
                {
                    b.HasOne("QuanLyDiem.Models.Entity.Course", "Course")
                        .WithMany("SectionClasses")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDiem.Models.Entity.Lecturer", "Lecturer")
                        .WithMany("SectionClasses")
                        .HasForeignKey("LecturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.SubGradeDetail", b =>
                {
                    b.HasOne("QuanLyDiem.Models.Entity.SectionClass", "SectionClass")
                        .WithMany()
                        .HasForeignKey("SectionClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDiem.Models.Entity.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionClass");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.Course", b =>
                {
                    b.Navigation("SectionClasses");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.Lecturer", b =>
                {
                    b.Navigation("SectionClasses");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.SectionClass", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("QuanLyDiem.Models.Entity.User", b =>
                {
                    b.Navigation("Lecturer");
                });
#pragma warning restore 612, 618
        }
    }
}
